export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_SINGLE_ARTICLE = 'GETTING SINGLE ARTICLE';
export const ARTICLE_LOADING = 'ARTICLE(S) LOADING';
export const GET_ARTICLE_ERROR = 'ERROR GETTING ARTICLE';
export const CLEAR_ARTICLE_ERROR = 'CLEARING ARTICLE ERROR';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const GET_ARTICLE_STAT = 'GETTING THE ARTICLE STATISTICS';
export const SET_ARTICLE_RATE = 'SETTING THE ARTICLE RATE';
