export const GET_PROFILE = 'GETTING USER PROFILE';
export const PROFILE_LOADING = 'LOADING USER PROFILE';
export const PROFILE_ERROR = 'GETTING PROFILE ERRORS';
export const GET_PROFILE_ARTICLES = 'GETTING PROFILE ARTICLES';
export const PROFILE_ARTICLES_LOADING = 'PROFILE ARTICLES LOADING';
